# permissions for end users to edit externalsecretcreates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalsecretcreate-editor-role
rules:
- apiGroups:
  - cache.jgavinray.dev
  resources:
  - externalsecretcreates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.jgavinray.dev
  resources:
  - externalsecretcreates/status
  verbs:
  - get
