# permissions for end users to view externalsecretcreates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalsecretcreate-viewer-role
rules:
- apiGroups:
  - cache.jgavinray.dev
  resources:
  - externalsecretcreates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.jgavinray.dev
  resources:
  - externalsecretcreates/status
  verbs:
  - get
