
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cache.jgavinray.dev
  resources:
  - externalsecretcreates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.jgavinray.dev
  resources:
  - externalsecretcreates/finalizers
  verbs:
  - update
- apiGroups:
  - cache.jgavinray.dev
  resources:
  - externalsecretcreates/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - secrets.jgavinray.dev
  resources:
  - externalsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.jgavinray.dev
  resources:
  - externalsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - secrets.jgavinray.dev
  resources:
  - externalsecrets/status
  verbs:
  - get
  - patch
  - update
